config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    resources :coincidences
  end
  resources :coincidences do
    collection do
      get :fetch_zone_people
    end
  end
  resources :people
  resources :comment_types
  resources :zones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/help", to: "home#help", as: "help"
  # Defines the root path route ("/")
  root "comments#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :comment_type
  has_many :coincidences, dependent: :destroy
end

app/models/comment_type.rb
class CommentType < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, except: %i[ index new create ]
  before_action :find_mmy, only: %i[ create ]

  # GET /comments or /comments.json
  def index
    @objections = Comment.all.where comment_type_id: 1
    @goods = Comment.all.where comment_type_id: 2
    @comments = Comment.all
    @coincidence = Coincidence.new
    @people = Person.all
  end

  # GET /comments/1 or /comments/1.json
  def show
    @zones = Zone.all
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @comment_types = CommentType.all
    @zones = Zone.all
    @people = Person.all

  end

  # GET /comments/1/edit
  def edit
    @comment_types = CommentType.all
    @zones = Zone.all
    @people = Person.all
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(
      title: comment_params[:title],
      description: comment_params[:description],
      comment_type_id: comment_params[:comment_type_id]
    )
    if @comment.save
      redirect_to @comment, notice: "comment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: "comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: "comment was successfully destroyed." 
  end

  def coincidence
    comment = Comment.find(params[:comment_id])
    person = Person.find(params[:person_id])
    if comment.people.includes?(person)
      redirect_to comments_url, notice: "Esta persona ya se añadió"
    else
      comment.people << person
    end
    redirect_to comments_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:title, :description, :number, :comment_type_id, :person_id)
    end

    def find_mmy
      @zone = Zone.find_by(id: params[:zone].presence)
      @person = Person.find_by(id: params[:person].presence)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <div class="card shadow">
    <div class="card-header m-2 p-3 d-flex justify-content-between">
      <h2><%= comment.title %> <span class="badge text-bg-primary"><%= comment.coincidences.count %></span></h2>
      <div class="btn-group">
        <div>
          <%= link_to "Editar", edit_comment_path(@comment), class: "btn btn-sm btn-warning" %>
        </div>
        <%= button_to "Eliminar", @comment, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
    <div class="card-body m-2 p-3">
      <div class="m-2 p-3">
        <%= comment.description %>
      </div>
      <div class="m-2 p-3">
        <div class="table-responsive">
          <table>
            <thead>
              <tr>
                <td>Persona</td>
                <td>Zona</td>
                <td>Descripción</td>
                <td colspan="2"></td>
              </tr>
            </thead>
            <tbody>
              <% comment.coincidences.each do |coincidence| %>
              <tr>
                <td><%= coincidence.person.name %></td>
                <td><%= coincidence.person.zone.name %></td>
                <td><%= coincidence.description %></td>
                <td><%= link_to "Ver", edit_comment_coincidence_path(comment, coincidence), class: "btn btn-sm btn-warning" %></td>
                <td><%= button_to "Eliminar", comment_coincidence_path(comment), method: :delete, class: "btn btn-sm btn-danger" %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>   
</div>

app/views/comments/_form.html.erb
<div class="row shadow">
  <%= turbo_frame_tag "this_form" do %>
    <%= form_with model: comment, data: { controller: "dropdown", action: "change->dropdown#submit" } do |form| %>
      <% if comment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="m-2">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="m-2">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, size: "70x5", class: "form-control" %>
      </div>

      <div class="m-2">
        <%= form.collection_select :comment_type_id, @comment_types, :id, :name, class:"form-select" %>
      </div>

      <div class="m-2">
        <%= form.submit "Guardar Comentario", class: "btn btn-sm btn-success" %>
      </div>

    <% end %>
  <% end %>
</div>

app/views/comments/_table_good.html.erb
<div class="m-2 p-3">
  <h2>Buenas prácticas</h2>
</div>
<div class="m-2 p-3 shadow">
  <table >
    <thead class="table-success">
      <tr>
        <td>Título</td>
        <td>Coincidencias</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% if @goods.empty? %>
        <tr>
          <td colspan="3">No hay comentarios creados todavía</td>
        </tr>
      <% else %>
        <% @goods.each do |comment| %>
          <tr> 
            <td><%= link_to comment.title, comment, title: comment.description %></td>
            <td><span class="badge text-bg-primary"><%= comment.coincidences.count %></span></td>
            <td><%= link_to "Añadir coincidencia", new_comment_coincidence_path(comment), class: "btn btn-sm btn-success" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/_table_objections.html.erb
<div class="m-2 p-3">
  <h2>Objeciones</h2>
</div>
<div class="m-2 p-3 shadow">
  <table>
    <thead class="table-danger">
      <tr>
        <td>Título</td>
        <td>Coincidencias</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% if @objections.empty? %>
        <tr>
          <td colspan="3">No hay objeciones creados todavía</td>
        </tr>
      <% else %>
        <% @objections.each do |comment| %>
          <tr> 
            <td><%= link_to comment.title, comment, title: comment.description %></td>
            <td><span class="badge text-bg-primary"><%= comment.coincidences.count %></span></td>
            <td><%= link_to "Añadir coincidencia", new_comment_coincidence_path(comment), class: "btn btn-sm btn-danger" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/edit.html.erb
<div class=" row m-2 shadow">
  <h1>Editando <%= @comment.title %></h1>
</div>
<div class=" row m-2">
  <%= render "form", comment: @comment %>
</div>
<div class=" row m-2 shadow">
  <%= link_to "Mostrar comentario", @comment, class: "btn btn-sm btn-primary" %>
  <%= link_to "Volver a comentarios", comments_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/comments/index.html.erb
<div class="row">
  <p style="color: green"><%= notice %></p>
</div>

<div class="m-2">
  <%= render "comments/table_objections" %>
</div>

<div class="m-2">
  <%= render "comments/table_good" %>
</div>

<div class="row m-2 shadow">
  <%= link_to "Agregar Comentario Nuevo", new_comment_path, class: "btn btn-sm btn-success" %>
</div>

app/views/comments/new.html.erb
<div class="row m-2 shadow">
  <h1>Nuevo Comentario</h1>
</div>

<div class=" row m-2">
  <%= render "form", comment: @comment %>
</div>

<div class=" row m-2 shadow">
  <%= link_to "Volver a comentarios", comments_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div class="row m-2 shadow">
  <%= link_to "Volver a Comentarios", comments_path, class: "btn btn-sm btn-dark" %>
</div>