config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    resources :coincidences
  end
  resources :coincidences do
    collection do
      get :fetch_zone_people
    end
  end
  resources :people
  resources :comment_types
  resources :zones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/help", to: "home#help", as: "help"
  # Defines the root path route ("/")
  root "comments#index"
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :zone
  has_many :coincidences, dependent: :destroy
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all.order(:zone_id)
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @zones = Zone.all
  end

  # GET /people/1/edit
  def edit
    @zones = Zone.all
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to comments_path, notice: "person was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    if @person.update(person_params)
      redirect_to @person, notice: "person was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    redirect_to people_url, notice: "person was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :zone_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="row shadow">
  <%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-2">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="m-2">
    <%= form.collection_select :zone_id, @zones, :id, :name, class: "form-selection" %>
  </div>

  <div class="m-2">
    <%= form.submit "Guardar Persona", class: "btn btn-sm btn-success" %>
  </div>
<% end %>
</div>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <div class="card shadow">
    <div class="card-header m-2 p-3 d-flex justify-content-between">
      <h2><%= person.name %></h2>
      <div class="btn-group">
        <div>
          <%= link_to "Editar", edit_person_path(@person), class: "btn btn-sm btn-warning" %>
        </div>
        <%= button_to "Eliminar", @person, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
    <div class="card-body">
      <%= person.zone.name %>
    </div>
  </div>   
</div>

app/views/people/edit.html.erb
<div class=" row m-2 shadow">
  <h1>Editando <%= @person.name %></h1>
</div>
<div class=" row m-2 shadow">
  <%= render "form", person: @person %>
</div>
<div class=" row m-2 shadow">
  <%= link_to "Mostrar #{@person.name}", @person, class: "btn btn-sm btn-primary" %>
  <%= link_to "Volver a personas", people_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/people/index.html.erb
<div class="row">
  <p style="color: green"><%= notice %></p>
</div>

<div class="row m-2 shadow">
  <h1>Personas</h1>
</div>

<div class="row m-2 shadow">
  <%= link_to "Agregar Persona", new_person_path, class: "btn btn-sm btn-success" %>
</div>

<div class="m-2 shadow">
  <div id="people">
    <table >
      <thead>
        <tr>
          <td>Nombre</td>
          <td>Zona</td>
        </tr>
      </thead>
      <tbody>
        <% if @people.empty? %>
          <tr>
            <td colspan="2">No hay personas creadas todavía</td>
          </tr>
        <% else %>
          <% @people.each do |person| %>
            <tr> 
              <td ><%= link_to person.name, person %></td>
              <td ><%= person.zone.name %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/people/new.html.erb
<div class="row m-2 shadow">
  <h1>Nueva Persona</h1>
</div>

<div class=" row m-2">
  <%= render "form", person: @person %>
</div>

<div class=" row m-2 shadow">
  <%= link_to "Volver a Personas", people_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div class="row m-2 shadow">
  <%= link_to "Volver a Personas", people_path, class: "btn btn-sm btn-dark" %>
</div>