config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    resources :coincidences
  end
  resources :coincidences do
    collection do
      get :fetch_zone_people
    end
  end
  resources :people
  resources :comment_types
  resources :zones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/help", to: "home#help", as: "help"
  # Defines the root path route ("/")
  root "comments#index"
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_many :people
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: %i[ show edit update destroy ]

  # GET /zones or /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1 or /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones or /zones.json
  def create
    @zone = Zone.new(zone_params)
    if @zone.save
      redirect_to @zone, notice: "Zone was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /zones/1 or /zones/1.json
  def update
    if @zone.update(zone_params)
      redirect_to @zone, notice: "Zone was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /zones/1 or /zones/1.json
  def destroy
    @zone.destroy
    redirect_to zones_url, notice: "Zone was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def zone_params
      params.require(:zone).permit(:name)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<div class="row shadow">
  <%= form_with(model: zone) do |form| %>
  <% if zone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
        <% zone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-2">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="m-2">
    <%= form.submit "Guardar Zona", class: "btn btn-sm btn-success" %>
  </div>
<% end %>
</div>

app/views/zones/_zone.html.erb
<div id="<%= dom_id zone %>">
  <div class="card shadow">
    <div class="card-header m-2 p-3 d-flex justify-content-between">
      <h2><%= zone.name %></h2>
      <div class="btn-group">
        <div>
          <%= link_to "Editar", edit_zone_path(@zone), class: "btn btn-sm btn-warning" %>
        </div>
        <%= button_to "Eliminar", @zone, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
  </div>   
</div>

app/views/zones/edit.html.erb
<div class=" row m-2 shadow">
  <h1>Editando <%= @zone.name %></h1>
</div>
<div class=" row m-2">
  <%= render "form", zone: @zone %>
</div>
<div class=" row m-2 shadow">
  <%= link_to "Mostrar #{@zone.name}", @zone, class: "btn btn-sm btn-primary" %>
  <%= link_to "Volver a zonas", zones_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/zones/index.html.erb
<div class="row">
  <p style="color: green"><%= notice %></p>
</div>

<div class="row m-2 shadow">
  <h1>Zonas</h1>
</div>

<div class="m-2 shadow">
  <div id="zones">
    <table >
      <thead>
        <tr>
          <td>Nombre</td>
        </tr>
      </thead>
      <tbody>
        <% if @zones.empty? %>
          <tr>
            <td>No hay zonas creadas todavía</td>
          </tr>
        <% else %>
          <% @zones.each do |zone| %>
            <tr> 
              <td ><%= link_to zone.name, zone %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row m-2 shadow">
  <%= link_to "Agregar zona", new_zone_path, class: "btn btn-sm btn-success" %>
</div>

app/views/zones/new.html.erb
<div class="row m-2 shadow">
  <h1>Nueva Zona</h1>
</div>

<div class=" row m-2">
  <%= render "form", zone: @zone %>
</div>

<div class=" row m-2 shadow">
  <%= link_to "Volver a zonas", zones_path, class: "btn btn-sm btn-dark" %>
</div>

app/views/zones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @zone %>

<div class="row m-2 shadow">
  <%= link_to "Volver a Zonas", zones_path, class: "btn btn-sm btn-dark" %>
</div>