config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    resources :coincidences
  end
  resources :coincidences do
    collection do
      get :fetch_zone_people
    end
  end
  resources :people
  resources :comment_types
  resources :zones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/help", to: "home#help", as: "help"
  # Defines the root path route ("/")
  root "comments#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <li><%= link_to "Comentarios", comments_path, class: "nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to "Personas", people_path, class: "nav-link" %></li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Configuracion
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Zonas", zones_path, class: "dropdown-item" %></li>
            <li><%= link_to "Tipos de Comentario", comment_types_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <li><%= link_to "Ayuda", help_path, class: "nav-link" %></li>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegendObjection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container justify-content-center p-3">
    <div >
      <%=render "layouts/navbar" %>
      <div class="container m-2 p-3 d-flex justify-content-center">
        <div class="col-8">
          <%= yield %>
        </div>
      </div>
    </div>
    

    <!-- Boostrap js-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

  </body>
</html>